[package]
authors = ["Sebastian Menski <sebastian.menski@camunda.com>"]
name = "zeebe-log-reader"
version = "0.1.0"

[dependencies]
failure = "0.1.1"
rmp-serde = "0.13.7"
serde = "1.0.24"
serde_bytes = "0.10.2"
serde_derive = "1.0.24"
structopt = "0.1.6"
structopt-derive = "0.1.6"
